### ISSUE TITLE
Please do not use

### ISSUE THREAD

**Issue by sarzali07** [qlint/L5-HRMS#2]
Hi Developer

Kindly upload updated code, as in your code nothing is functional. I installed it many problems I found like mishandling of URL, submitting URLs etc.

My advice is to kindly upload fresh working code or remove this repository 

Regards

**Comment by qlint** [comment]
Hi,
KIndly use the code from the original developer : https://github.com/kmanjari/hrms There's a demo link there as well. Due to time constraints, I've been unable to update this one.
